apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  serviceName: {name}
  replicas: 1
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      volumes:
      - name: data-volume
        hostPath:
          path: /var/data/cassandra
      containers:
      - name: {name}
        image: cassandra:3.11.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/lib/cassandra
          name: data-volume
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          limits:
            cpu: "500m"
            memory: 2Gi
          requests:
            cpu: "500m"
            memory: 2Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
        - name: MAX_HEAP_SIZE
          value: 1096M
        - name: HEAP_NEWSIZE
          value: 358M
        - name: CASSANDRA_CLUSTER_NAME
          value: "Subiz CASCLUS"
        - name: CASSANDRA_DC
          value: "DC1-K8Demo"
        - name: CASSANDRA_RACK
          value: "Rack1-K8Demo"
        - name: CASSANDRA_AUTO_BOOTSTRAP
          value: "false"
---
kind: Service
apiVersion: v1
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  selector:
    app: {name}
  clusterIP: None
  ports:
  - protocol: TCP
    port: 9042
    targetPort: 9042
