kind: Service
apiVersion: v1
metadata:
  name: {name}-0
  labels:
    app: {name}-0
spec:
  clusterIP: None
  ports:
  - protocol: TCP
    port: 9042
    targetPort: 9042
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {name}-0
subsets:
- addresses:
  - ip: 35.184.126.126
  ports:
  - port: 9042
