
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "bitbucket.org/subiz/conversation"

[[constraint]]
  name = "bitbucket.org/subiz/gocommon"
  version = "1.0.8"

[[constraint]]
  name = "bitbucket.org/subiz/header"
  version = "1.0.7"

[[constraint]]
  name = "bitbucket.org/subiz/id"
  version = "0.1.5"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/gocql/gocql"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/orcaman/concurrent-map"

[[constraint]]
  branch = "master"
  name = "github.com/pquerna/ffjson"

[[constraint]]
  branch = "master"
  name = "github.com/thanhpk/goslice"
